//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WIN.SCHEDULING_APP.GUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Agenda")]
        public string Main_AppName {
            get {
                return ((string)(this["Main_AppName"]));
            }
            set {
                this["Main_AppName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("iMaginary")]
        public string Main_AppStyleName {
            get {
                return ((string)(this["Main_AppStyleName"]));
            }
            set {
                this["Main_AppStyleName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Home")]
        public string Main_StartCommand {
            get {
                return ((string)(this["Main_StartCommand"]));
            }
            set {
                this["Main_StartCommand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Main_MaxResult {
            get {
                return ((int)(this["Main_MaxResult"]));
            }
            set {
                this["Main_MaxResult"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Main_Province {
            get {
                return ((string)(this["Main_Province"]));
            }
            set {
                this["Main_Province"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Main_Comune {
            get {
                return ((string)(this["Main_Comune"]));
            }
            set {
                this["Main_Comune"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Main_DeadlineDaysBefore {
            get {
                return ((int)(this["Main_DeadlineDaysBefore"]));
            }
            set {
                this["Main_DeadlineDaysBefore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Giornaliera")]
        public string Main_Calendar_ViewType {
            get {
                return ((string)(this["Main_Calendar_ViewType"]));
            }
            set {
                this["Main_Calendar_ViewType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Appuntamento")]
        public string Main_CalendarSubject {
            get {
                return ((string)(this["Main_CalendarSubject"]));
            }
            set {
                this["Main_CalendarSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_ProductionEnvironment {
            get {
                return ((bool)(this["Main_ProductionEnvironment"]));
            }
            set {
                this["Main_ProductionEnvironment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_ViewTaskDetails {
            get {
                return ((bool)(this["Main_ViewTaskDetails"]));
            }
            set {
                this["Main_ViewTaskDetails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Attività")]
        public string Main_TaskSubject {
            get {
                return ((string)(this["Main_TaskSubject"]));
            }
            set {
                this["Main_TaskSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Main_MarkActivityCompletedafterDragDrop {
            get {
                return ((bool)(this["Main_MarkActivityCompletedafterDragDrop"]));
            }
            set {
                this["Main_MarkActivityCompletedafterDragDrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Main_AskIfActivityMustbeMarkedAsCompleted {
            get {
                return ((bool)(this["Main_AskIfActivityMustbeMarkedAsCompleted"]));
            }
            set {
                this["Main_AskIfActivityMustbeMarkedAsCompleted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Main_RenewActivityAfterDragDrop {
            get {
                return ((bool)(this["Main_RenewActivityAfterDragDrop"]));
            }
            set {
                this["Main_RenewActivityAfterDragDrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Main_AskIfRenewActivityAfterDragDrop {
            get {
                return ((bool)(this["Main_AskIfRenewActivityAfterDragDrop"]));
            }
            set {
                this["Main_AskIfRenewActivityAfterDragDrop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int Main_DaysOfRenewTask {
            get {
                return ((int)(this["Main_DaysOfRenewTask"]));
            }
            set {
                this["Main_DaysOfRenewTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_ActivateTaskPanelOnCalendar {
            get {
                return ((bool)(this["Main_ActivateTaskPanelOnCalendar"]));
            }
            set {
                this["Main_ActivateTaskPanelOnCalendar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_OtherApp {
            get {
                return ((bool)(this["Main_OtherApp"]));
            }
            set {
                this["Main_OtherApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Main_CalendarGroupType {
            get {
                return ((int)(this["Main_CalendarGroupType"]));
            }
            set {
                this["Main_CalendarGroupType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_FillAppointmentLocationWithCustomerAddress {
            get {
                return ((bool)(this["Main_FillAppointmentLocationWithCustomerAddress"]));
            }
            set {
                this["Main_FillAppointmentLocationWithCustomerAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Main_StartInitialSearch {
            get {
                return ((bool)(this["Main_StartInitialSearch"]));
            }
            set {
                this["Main_StartInitialSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_InsertJolly {
            get {
                return ((bool)(this["Main_InsertJolly"]));
            }
            set {
                this["Main_InsertJolly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oggetto documento")]
        public string Main_DocumentDefaultSubject {
            get {
                return ((string)(this["Main_DocumentDefaultSubject"]));
            }
            set {
                this["Main_DocumentDefaultSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Main_PreviewDocument {
            get {
                return ((bool)(this["Main_PreviewDocument"]));
            }
            set {
                this["Main_PreviewDocument"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1900-01-01")]
        public global::System.DateTime Main_LastBack {
            get {
                return ((global::System.DateTime)(this["Main_LastBack"]));
            }
            set {
                this["Main_LastBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Progressive")]
        public string Main_ProtocolStrategy {
            get {
                return ((string)(this["Main_ProtocolStrategy"]));
            }
            set {
                this["Main_ProtocolStrategy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Main_PanelCollapsed {
            get {
                return ((bool)(this["Main_PanelCollapsed"]));
            }
            set {
                this["Main_PanelCollapsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Main_ShowOnlyAgendaFunctions {
            get {
                return ((bool)(this["Main_ShowOnlyAgendaFunctions"]));
            }
            set {
                this["Main_ShowOnlyAgendaFunctions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Main_Nazione {
            get {
                return ((string)(this["Main_Nazione"]));
            }
            set {
                this["Main_Nazione"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Main_ZoomTemporale {
            get {
                return ((int)(this["Main_ZoomTemporale"]));
            }
            set {
                this["Main_ZoomTemporale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Main_ZoomSpaziale {
            get {
                return ((int)(this["Main_ZoomSpaziale"]));
            }
            set {
                this["Main_ZoomSpaziale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("169.254.0.20")]
        public string networkdomain {
            get {
                return ((string)(this["networkdomain"]));
            }
            set {
                this["networkdomain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fenealuil13")]
        public string networkpassword {
            get {
                return ((string)(this["networkpassword"]));
            }
            set {
                this["networkpassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("protocollo")]
        public string networkusername {
            get {
                return ((string)(this["networkusername"]));
            }
            set {
                this["networkusername"] = value;
            }
        }
    }
}
